from sys import argv
script , file_name = argv
print(f"We are going to erase {file_name}!")
print("Cancel >> CTRL+C")
print("DELETE >> RETURN")
input("...?")
print("Openning the file...")
target = open(file_name , 'w')
print("Truncating the file!")
target.truncate()
print("add lines :3")
l1 = input("line1: ")
l2 = input("line2: ")
l3 = input("line3: ")
print("adding these lines to the file")
# target.write(l1)
# target.write("\n")
# target.write(l2)
# target.write("\n")
# target.write(l3)
target.write(l1+"\n"+l2+"\n"+l3)
print("closing the file")
target.close()
